### ISSUE TITLE
showing up as FabISP on mac

### ISSUE THREAD

**Issue by bmoren** [sparkfun/Tiny-AVR-Programmer#6]
Anyone else having issues on mac?

Tested on
10.13.4 // via USB hub / USBC dongle
with Crosspack  avrdude

![Screen Shot 2019-10-28 at 3 08 18 PM](https://user-images.githubusercontent.com/1385996/67713934-d83f1680-f994-11e9-90d8-f9a8b5138005.png)

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. I noticed this question when browsing our issues.

**Renaming USB Device**

I'm not sure if this is really an issue? Depending on what is installed with an OS, the device may show up as "**FabISP**" but it should still function as an AVR programmer.  I've seen this happen on a Windows OS. I was still able to flash an AVR chip as long as I selected "**USBtinyISP**" as the programmer via the Arduino IDE or using "**usbtiny**" for AVRDUDE's programmer type via command line. To adjust the name, I used "[Zadig](https://learn.sparkfun.com/tutorials/tiny-avr-programmer-hookup-guide#automatic-install)". It looks like that software is only for Windows.

If you really want to rename the device on a Mac, there may be a way. I am not sure the exact details on adjusting the name. Most forums suggest that you are not able to change the USB device name. However, there was one forum that indicated you may be able to rename the attached USB device by using an "alias" and writing a bash script to make it permanent. You may have to adjust the permissions to enable the script.

**Issues Flashing an AVR Chip**

If I had any issues flashing an AVR chip, I simply uninstalled the device using the Window's Device Manager and reinstalled with Zadig. If there are issues flashing an AVR chip, you may need to take additional troubleshooting steps. It looks like your AVR programmer is already on a USB 2.0 hub, so you probably have not seen any issues flashing an AVR chip.

**Still Having Issues?**

If you still have issues, you may want to check out the following forums for further assistance or additional methods:

* [SparkFun Forums](https://forum.sparkfun.com/)
* [Arduino Forums](https://forum.arduino.cc/)
* [Arduino Stack Exchange](https://arduino.stackexchange.com/)
